### ISSUE TITLE
I removed this notification . But , an error.

### ISSUE THREAD

**Issue by ashokkumarvel** [dkrivoruchko/ScreenStream#100]
I removed this code https://github.com/dkrivoruchko/ScreenStream/blob/master/app/src/main/kotlin/info/dvkr/screenstream/service/helper/NotificationHelper.kt . 

Then , I run the app. But , it comes like this.

![Screenshot_20200621-184442_ScreenStream](https://user-images.githubusercontent.com/65845270/85225560-e0e6d000-b3ef-11ea-97da-0f3f4092ef72.jpg)

Help!!!

**Comment by dkrivoruchko** [comment]
Add it back

**Comment by ashokkumarvel** [comment]
Can you give more information?

**Comment by dkrivoruchko** [comment]
Notifications are mandatory. If you remove them app will not work

**Comment by ashokkumarvel** [comment]
There , how can I remove it .
