### ISSUE TITLE
Gradle build failed. 

### ISSUE THREAD

**Issue by ashokkumarvel** [dkrivoruchko/ScreenStream#101]
I want to add this plugin   : apply plugin: 'com.growingio.android' .

When I build gradle  with this plugin It comes could not find I'd.

I used this plugin in my another app. This plugin  syc perfectly in that project.  

How can I add this plugin in this project?

**Comment by ashokkumarvel** [comment]
I want to add this plugin 


apply plugin: 'com.growingio.android'


And these dependencies 


implementation fileTree(dir: 'libs', include: "*.jar")
--
  | implementation deps.supportAppCompat
  | implementation deps.supportDesign
  | implementation deps.butterknife
  | implementation deps.swipeRevealLayout
  | implementation deps.glide
  | implementation deps.growingio
  | annotationProcessor deps.glideCompiler
  | annotationProcessor deps.butterknifeCompiler
  | implementation(deps.rxbus) {
  | exclude group: 'com.jakewharton.timber', module: 'timber'
  | }
  | implementation deps.androidasync
  | implementation deps.timber

  |  

How can add ?

**Comment by dkrivoruchko** [comment]
You have to read docs for  growingio plugin and docs for dependencies you want to add

**Comment by ashokkumarvel** [comment]
Can you give more information?

**Comment by ashokkumarvel** [comment]
Help !!!

**Comment by dkrivoruchko** [comment]
I cannot find any docs for growingio.android. May be you have any docs?
Dependencies listed are not a correct id's for dependencies. You just copied test with out understanding it.
Almost all of them are outdated/incompatible or simple does not required.
