### ISSUE TITLE
buld error.

### ISSUE THREAD

**Issue by PradeepSimba** [dkrivoruchko/ScreenStream#103]
when I add dependencies it comes an error like this.

`Could not get unknown property 'deps' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

**Comment by dkrivoruchko** [comment]
I have no idea what `deps` is

**Comment by ashokkumarvel** [comment]
How to add dependencies

**Comment by PradeepSimba** [comment]
When I add plugin it comes plugin  not found.
