### ISSUE TITLE
Problem when adding plugins and dependencies. 

### ISSUE THREAD

**Issue by PradeepSimba** [dkrivoruchko/ScreenStream#104]
When I add any plugin it comes ` plugin not found.`

When I add any dependencies it comes 

`Could not get unknown property 'deps' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
`
why it comes like this ? 

Can you give a solution for this?

I tried to add dependencies  and plugins for 2 days. But , all fails.

help !!!

**Comment by dkrivoruchko** [comment]
https://medium.com/@sushanthande1/dependency-management-in-android-studio-cc4352122dcf
