### ISSUE TITLE
How to add a plugin with this project ?

### ISSUE THREAD

**Issue by ashokkumarvel** [dkrivoruchko/ScreenStream#105]
How can I add this plugin with this project?

I spended two weeks for this. But , all fails

apply plugin: 'com.growingio.android'

When I add this it comes an error  like this

`Plugin with id 'com.growingio.android' not found`

When I add any plugin it comes `Plugin not found` .

Help me!!!

**Comment by dkrivoruchko** [comment]
https://growingio.gitbook.io/docs/developer-manual/sdkintegrated/android-sdk/auto-android-sdk

**Comment by ashokkumarvel** [comment]
I successfully added this plugin.

But , When I build this it comes an error like this.



`
> Task :app:processFirebaseDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{}],"original":"AAPT: error: resource style/AppTheme (aka info.dvkr.screenstream:style/AppTheme) not found.\nerror: failed linking references.\n\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processFirebaseDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource style/AppTheme (aka info.dvkr.screenstream:style/AppTheme) not found.
     error: failed linking references.
     `

**Comment by dkrivoruchko** [comment]
First you have to switch to FirebaseFree build type and then check for AppTheme tin recourses/styles

**Comment by ashokkumarvel** [comment]
AndroidManifest.xml
  
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <application
        android:name=".ScreenStreamApp"
        android:allowBackup="true"
        android:fullBackupContent="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.App.DayNight"
        tools:ignore="GoogleAppIndexingWarning">
        <activity android:name=".ui.activity.AppActivity" />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <data android:scheme="growing.1f3e3791e1d6aee5" />
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name=".service.AppService"
            android:exported="false"
            android:foregroundServiceType="mediaProjection"
            tools:targetApi="q" />
        <service
            android:name=".service.TileActionService"
            android:icon="@drawable/ic_tile_default_24dp"
            android:label="@string/app_name"
            android:permission="android.permission.BIND_QUICK_SETTINGS_TILE">
            <intent-filter>
                <action android:name="android.service.quicksettings.action.QS_TILE" />
            </intent-filter>
        </service>

        <receiver
            android:name=".receiver.BootReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
            </intent-filter>
        </receiver>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="info.dvkr.screenstream.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>

    </application>

How can I solve this?

**Comment by ashokkumarvel** [comment]
How can I  switch to FirebaseFree build type ?

**Comment by ashokkumarvel** [comment]
help!!!
