### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [dkrivoruchko/ScreenStream#107]
Since you bring an AAR: https://github.com/dkrivoruchko/ScreenStream/commit/79516902856769efcf9860718f65b3e8e6034914#diff-39e7d8c00954e920b98e7636f0ac30b2R102

Where's its source code?

**Comment by dkrivoruchko** [comment]
Why you need it's source code ?
Its a a bottom sheet dialog lib with fix for this https://github.com/afollestad/material-dialogs/issues/1825

**Comment by licaon-kter** [comment]
Because F-Droid hosts only fully FOSS apps build from source or with artefacts taken from maven repos that host only fully FOSS stuff.

Where's the source code for your fix? We'd need to build that and move the resulting AAR in place.

**Comment by dkrivoruchko** [comment]
This is a project https://github.com/afollestad/material-dialogs
arr is a for "bottomsheets" module from this project with this line removed.
https://github.com/afollestad/material-dialogs/blob/66582d9993bcf55bfea873b4bf484a429ce3df36/bottomsheets/src/main/java/com/afollestad/materialdialogs/bottomsheets/BottomSheet.kt#L241

**Comment by rugk** [comment]
Any news here? It would be good to have an up-to-date version in F-Droid?

**Comment by dkrivoruchko** [comment]
3.4.11 expected to be ok for F-Droid to build

**Comment by licaon-kter** [comment]
FYI https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7690

**Comment by dkrivoruchko** [comment]
Just comment line 99: https://github.com/dkrivoruchko/ScreenStream/blob/d0cf9f09f01326d9f832cf6320e4f3f6f50982e8/app/build.gradle#L99
And uncomment line 100: https://github.com/dkrivoruchko/ScreenStream/blob/d0cf9f09f01326d9f832cf6320e4f3f6f50982e8/app/build.gradle#L100
This will allow to build app, but this library has a bug https://github.com/afollestad/material-dialogs/issues/1825 which is still not fixed.
In release 3.4.11 I did so but got too many crashes in production, so I revert back to my fix.

**Comment by licaon-kter** [comment]
Not sure why you'd repeat that, I already got what the issue is. And letting is crash later is no solution.

**Comment by licaon-kter** [comment]
Could you reopen this? It's not actually fixed...

Also, can you guide me on how to build the AAR from source?

**Comment by dkrivoruchko** [comment]
To build the same fixed `bottomsheets-release.aar` (version 3.3.0)
1. Clone https://github.com/afollestad/material-dialogs
2. Remove line 241: https://github.com/afollestad/material-dialogs/blob/165eb41dcfca31abab4a42341aa7f9f5aae53596/bottomsheets/src/main/java/com/afollestad/materialdialogs/bottomsheets/BottomSheet.kt#L241
3. Build release aar: `gradle bottomsheets:assembleRelease`
4. Result: `bottomsheets-release.aar`

**Comment by licaon-kter** [comment]
Better

ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7694

@dkrivoruchko do ping us when the situation changes
