### ISSUE TITLE
[Feature request] Start stream from another app

### ISSUE THREAD

**Issue by KuboCh** [dkrivoruchko/ScreenStream#109]
Hi, can you make an intent that will start ScreenStream application and also start the streaming of screen on the background from another app?

**Comment by dkrivoruchko** [comment]
You don't need any specific Intent, Just run a default start for MainActivity and activate in app settings - "Auto start/stop streaming".
Keep in mind Permissions request dialog!

**Comment by KuboCh** [comment]
Yeah but default intent for MainActivity will bring app in foreground, which i don't want, I have activated settings "Auto start/stop streaming", but it doesn't start streaming when the app is in background, I don't getting permissions request dialog on android 6.0.1, btw can it be granted one time for all? On android 10 it shows every time the stream is starting.

**Comment by dkrivoruchko** [comment]
Before Android 10 there was an option "Never ask again". On 10+ there is no.
In any case on any Android version you need some Activity to request a permission (even if it will be approved automatically).
This mean app has to be in foreground to that.
So no auto start on background.

**Comment by KuboCh** [comment]
I see, last question would you consider creating library for streaming from your app? For other apps to implement streaming feature.

**Comment by dkrivoruchko** [comment]
Noop
