### ISSUE TITLE
Licensing!!!

### ISSUE THREAD

**Issue by abiange** [dkrivoruchko/ScreenStream#114]
I have some doubts about the licenses.

I would like to add the sound feature in this app and upload it to the Play Store.

May I have permission for this?

I heard this because someone is already publishing your app without any changes.

https://play.google.com/store/apps/details?id=com.onedayofcode.screenmirror

**Comment by abiange** [comment]
I want to publish this project with some modification.

May I have permission for this?

**Comment by kamolsrisan** [comment]
good

**Comment by dkrivoruchko** [comment]
You may do whatever you want but you have to keep full original MIT license (Including author name).
So this clone https://play.google.com/store/apps/details?id=com.onedayofcode.screenmirror violating license.

**Comment by abiange** [comment]
How to get the full original MIT license ?

Can you give more information?
Because,  I didn't know about licensing.

**Comment by dkrivoruchko** [comment]
https://github.com/dkrivoruchko/ScreenStream/blob/master/LICENSE

**Comment by abiange** [comment]
I didn't know about licensing. 

Where to include this license?

is this license enough for publishing?

**Comment by dkrivoruchko** [comment]
In app (as a text or a link)
It's enough but will be nice if you note an original project (this one)

**Comment by abiange** [comment]
thanks for your reply!!!

**Comment by kamolsrisan** [comment]
good

**Comment by rugk** [comment]
Also it would be even better to contribute your changes back here, i.e. create a pull request to submit your changes to this project back.
For information on how to propose PRs, see https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/. See [this article](https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/) for how to merge upstream changes into your fork.
