### ISSUE TITLE
CORS capabilities

### ISSUE THREAD

**Issue by pocce90** [dkrivoruchko/ScreenStream#123]
If we try to use generated stream inside an external page (inside canvas), we receive the error "canvas is not origin-clean"...so, it's possible to add a flag that enables CORS capabilities? (Access-Control-Allow-Origin)

**Comment by dkrivoruchko** [comment]
Basically, you asking to add header `Access-Control-Allow-Origin: *` to http page with stream?
Maybe it's simpler just to point to MJPEG stream itself?

**Comment by pocce90** [comment]
We need an HTMLMediaElement to obtain MediaStream, so we could't use mjpeg because is a HTMLImageElement. For this we tring to draw video inside canvas and use canvas.captureStream() to obtain it.

**Comment by dkrivoruchko** [comment]
Ok, will `Access-Control-Allow-Origin: *` help you?

**Comment by pocce90** [comment]
yes, exactly.

**Comment by dkrivoruchko** [comment]
ok. will be in next release

**Comment by pocce90** [comment]
Ohh, good. Thanks.
