### ISSUE TITLE
over USB tethering

### ISSUE THREAD

**Issue by jawadahmeddogar** [dkrivoruchko/ScreenStream#124]
hi,
I enabled and selected local host only  and turned on usb tethering on my android and connected it to my pc .At my pc i tried to access it through 127.0.0.1:8080 but not succeeded ... any solution ...??

**Comment by dkrivoruchko** [comment]
Settings a wrong. You have to:
1. Disable "Use wifi only:
2. Disable "Enable local host" - useless in that case
3. turn on and connect usb tethering
Now go to the address that is not from wifi

**Comment by jawadahmeddogar** [comment]
thanks...solved...   any plans in future to add audio also in the stream....??
