### ISSUE TITLE
[Feature] how can I do to use this project as a API with another apps?

### ISSUE THREAD

**Issue by cartovarc** [dkrivoruchko/ScreenStream#126]
Hi! This project is awesome, we need use it as a feature in another app.. how could I do this?

Thanks!!!

**Comment by dkrivoruchko** [comment]
Can you be more specific what you want to achieve?

**Comment by yatoooon** [comment]
I guess he means How to quickly integrate it into other projects

**Comment by cartovarc** [comment]
Hello, we would like to include only some functionalities in an already created project. We would like to use it as a streaming method for a drone camera and to be able to process video with opencv. At the moment we are using "screen stream" but we must run both applications.

If we could use this project as a library or API, we could contribute to that project. How could this start?

**Comment by vikrant123pundir** [comment]
- Are you making that project for personal use only? If yes , then I have a workaround to this...
Mind you, I am not a android programmer like you guys, so my workaround might be worth laughing at.
You interested???

**Comment by dkrivoruchko** [comment]
@cartovarc this app does not stream video. It stream MJPEG.

**Comment by leson-jawa** [comment]
if for drones certainly no audio stream is needed
