### ISSUE TITLE
„Resize image“ is not working as intended for me (or described wrong?)

### ISSUE THREAD

**Issue by jfml** [dkrivoruchko/ScreenStream#13]
Hey, first of all, I love this app, I've wanted something like this for years!

But the resize image-setting says I can set a percent value of 10-150% (if I understand correctly) but I can only write two digits in the field, so I can't even get 100% of my phone's resolution only 99%.

![screenshot_20180126-092354](https://user-images.githubusercontent.com/4312909/35431018-246ce91e-027b-11e8-81fd-c24211b298d7.png)

I'm using the 2.1.4 version on Lineage 14.1 (Android 7.1.2)

If you need any further info I'd be happy to provide. Thanks again!

**Comment by dkrivoruchko** [comment]
Fixed in 2.1.5
Please update.

**Comment by jfml** [comment]
Yay! Thanks!
