### ISSUE TITLE
[Feature] Option for a totally blank screen on stopping transmission.

### ISSUE THREAD

**Issue by vikrant123pundir** [dkrivoruchko/ScreenStream#130]
I use this app as a teacher to project phone's screen on board. Sometimes I need to use my phone in between, like searching for an image.
But I don't want that to be projected on board, so I stop transmission. But that also project a blue box on the board which kind of distracts students.
Can I have an option for a totally blank screen instead of blue background with logo.
Thanks.

**Comment by hebertcisco** [comment]
@dkrivoruchko Would this be feasible? Is it within the scope of your project?

**Comment by dkrivoruchko** [comment]
Ok, will do.

**Comment by dkrivoruchko** [comment]
Check in 3.8.5.
Settings - Interface - Show "Press START on device"
