### ISSUE TITLE
zh/strings.xml对画质的描述有误

### ISSUE THREAD

**Issue by huacius** [dkrivoruchko/ScreenStream#135]
<string name="pref_jpeg_quality_summary">设置 JPEG 压缩画质</string>
    <string name="pref_jpeg_quality_dialog">顺时针旋转方向.\n值: 10–100 (默认: 80)</string>
此句应为对画质的描述，不是对旋转方向的描述。

**Comment by dkrivoruchko** [comment]
Just give correct translation, please.

**Comment by huacius** [comment]
> Just give correct translation, please.

recommend to replace with “设置JPEG压缩画质” or remove it.
![Screenshot_20201202-084934_TeslaCast](https://user-images.githubusercontent.com/72131616/100814734-4e0d8f80-347d-11eb-8411-7cae9dc1b4bf.jpg)

**Comment by huacius** [comment]
solved.
