### ISSUE TITLE
Installed the App 3.5.3 And I get a permission error

### ISSUE THREAD

**Issue by RobPiosik** [dkrivoruchko/ScreenStream#138]
I installed 3.5.3 from Play Store and installed on Galaxy Tab A Android 7.0 . When installing the application, the permission screen says "This application does not require any special permissions". When running the app after installation, pressing "Start Stream" shows a dialog box reading "Screen Stream will start capturing everything that's displayed on your screen." I am unable to proceed by tapping the "start now" button. If I tap "cancel", a dialog reading "Application requires Screen Cast permission to capture screen."

When I run the same application on my Note 10 with Android 10 it runs flawless. Its a great App but I want to stream my Tab A and not the Phone. Thanks

**Comment by dkrivoruchko** [comment]
You must accept permissions request on Tab.
