### ISSUE TITLE
Scaling max 99%

### ISSUE THREAD

**Issue by Wiredframe** [dkrivoruchko/ScreenStream#14]
I really like ScreenStream, it's perfect for presentations and stuff without Chromecast. Only thing I noticed is that I can only enter two-digit numbers in the image scaling settings. It should be 10-150 instead.

**Comment by dkrivoruchko** [comment]
Duplicate #13 
Fixed in 2.1.5
Please update.

**Comment by Wiredframe** [comment]
Didn't see that, sorry :) and thanks!!
