### ISSUE TITLE
Hide the port on Browser

### ISSUE THREAD

**Issue by tutan123** [dkrivoruchko/ScreenStream#140]
I have a problem when some browser on my car cannot visit the IP address with port number , how can i hide the port? i changed the code and set 80 as port but it accurred nettyServerException/

How can i solve the problem, thank you .

**Comment by tutan123** [comment]
I find that linux don't allow port number <1024 for no root right machine

**Comment by tutan123** [comment]
How can i hide the port and visit the ip using my car browser like Tesla's Broswer?

**Comment by dkrivoruchko** [comment]
You cannot set port number lower than 1024. This is Android system limitation.
And it's really strange that you cannot visit IP Address with port number. Check if type it correctly.

**Comment by tutan123** [comment]
Thanks for your reply.
Becasu i use it on Tesla Model 3's browser. It banned the local ip with port, but without port it can access, so my request is can we hide the port?

**Comment by dkrivoruchko** [comment]
No
