### ISSUE TITLE
How can I view the stream on SurfaceView or CanvasView?

### ISSUE THREAD

**Issue by jayesh83** [dkrivoruchko/ScreenStream#143]
I'm using features of ScreenStream i.e. capturing screen and streaming. The current implementation is amazing but I want something specific. I'm building an app to app streaming and not from app to WebView or Browser to be involved. And for that, I'm sure that I'll have to use SurfaceView or CanvasView or something of this sort. But I'm not sure exactly how. Can anyone suggest how can I achieve this?
@dkrivoruchko @WaldiSt @tiborepcek

**Comment by dkrivoruchko** [comment]
The stream is in MJPEG format but for app to app you may just use [Android Broadcast mechanism](https://developer.android.com/guide/components/broadcasts) (Not LocalBroadcastManager) and just stream jpeg images. But I'm unsure if broadcast speed will be enough.

**Comment by dkrivoruchko** [comment]
Another option is to use localhost, connect to it from new app and parse mjpeg stream (or update Screen Stream to publish JPEGs via some simple json api call)

**Comment by jayesh83** [comment]
Okay thank you so much for the approaches. I'll surely implement both of them and write here about the same. I'll keep this open untill all finalized. Thank You 🔆

**Comment by jayesh83** [comment]
There's slite confusion I guess. Actually, I'm not concerned about transferring MJPEG or images or connections between client and server. It is about how to view incoming data on SurfaceView or CanvasView natively in android. I'm not getting how the browser is receiving MJPEGs, parsing it, and showing them on the screen. Currently, I'm using a webview inside ScreenStream and there I'm showing the receiver side screen and not in the browser. But now I want a native viewer where I can achieve the same goal.

Steps I want to implement.
1. Server starts the connection _[done]_
2. Client types/scans the address in the app itself and connection established _[done]_
3. Server sending MJPEG/stream/images _[done]_
4. Client should receive MJPEG/stream, render it and show on the SurfaceView or any compatible consumer view _[want to achive]_

How to receive stream inside the app itself, render it and show it on some view?

Also, I'm intermediate so step by step guide will help me clearly understand your approach.
Thank you👍

**Comment by dkrivoruchko** [comment]
The easiest way is in this new app to make a network call to http://127.0.0.1:8080/stream.mjpeg (Assuming that ScreanStream server running on local host) and parse jmpeg stream for jpeg bytes (Google this). Then show jpeg in SurfaceView.

**Comment by jayesh83** [comment]
Sure! Yes. That sounds like a good start. Thanks, I'll start implementing that. And also is there any problem if I keep the server on the current implementation of ScreenStream and not change it to a local host?

**Comment by dkrivoruchko** [comment]
ScreenStream already can work on localhost, just use current app version.

**Comment by jayesh83** [comment]
Yes alright!

**Comment by jayesh83** [comment]
There's a package called Grafika. can you tell me what's that used for exactly? it has something to do with capturing the screen but not getting it exactly.
