### ISSUE TITLE
Use stream URL as IP Camera stream (with ManyCam software)

### ISSUE THREAD

**Issue by doubledave04** [dkrivoruchko/ScreenStream#145]
I am trying to find a way to use an android tablet/phone as a whiteboard for the ManyCam software with Screen Stream HTTP. ManyCam allows adding either IP Camera link (HTTP) or RTMP Stream but it won't show the stream coming out of Screen Stream HTTP for some reason. Do you know how I can resolve this?

Much thanks!

**Comment by dkrivoruchko** [comment]
First - it has to be a working network connection from ManyCam to Screen Stream.
Second - use mjpeg link in ManyCam, like http://192.168.0.100/stream.mjpeg

**Comment by doubledave04** [comment]
That worked! Though it's a bit flaky. Sometimes it connects, sometimes not, I have to re-try a few times. And when it does connect, there's a few seconds delay. Am I doing sothing wrong? I had the link on ManyCam as http://192.168.1.97:8080/stream.mjpeg

**Comment by dkrivoruchko** [comment]
Noop. Looks good. Delay can be because of slow network, slow phone, and many other reasons.
Check if stream in browser is ok.

**Comment by zireli0011** [comment]
my your help
