### ISSUE TITLE
Shared Screen gets cropped after turning the screen to sleep and then waking up. 

### ISSUE THREAD

**Issue by kartikmodi** [dkrivoruchko/ScreenStream#146]
First, thanks a lot for making such a wonderful OSS app.

Behaviour -
The screen get trimmed when the phone is made to sleep with sing click power button  (normal operation) and then again waked up. 
The how-much trim is proportional to the value set in Resize Image configuration. 
Like I have configured 65% because it's just the right number which covers my whole desktop screen in browser. 

The issue happens only when Resize Image is set anything less than 100%. 
When resize image is set to 100% there's NO ISSUE and everything works as expected. 

ScreenShot - (For some reason GitHub isn't accepting this image in attachment) So - 
https://i.imgur.com/WbBGQPZ.png

Please have a look. 
I can share whatever logs are required, provided I understand the steps to turn on the logs. 

Phone Details - 
Xiaomi Mi A3  (laural_sprout) 
crDroid (Android 10) 
Rooted 
No Conflicting apps 
Issue Type - 100% Re-creatable 

FYI - 
I also have a OnePlus Nord phone with official OS installed (non-rooted) and the issue doesn't happen there. 
I understand the questioned stability of ROMs but I AFAI understand this issue should not be related to any of things modified by ROMs in general.

**Comment by dkrivoruchko** [comment]
Ok. Please send me app logs. 
TO enable logging in app go to about page, tap 5 times (or more) on app version, than go to app settings - advanced and enable "Enable application logs".
Reproduce an issue and send log to me in email.

**Comment by kartikmodi** [comment]
@dkrivoruchko I have sent you the logs through this process. Let me know if you didn't receive it.

**Comment by dkrivoruchko** [comment]
Yes, I got the logs, but there is no issues.
I have no idea what is wrong.
What if you rotate device screen to landscape and back, will it fix issue?
