### ISSUE TITLE
playstore , Licensing and ads.

### ISSUE THREAD

**Issue by parasuraam** [dkrivoruchko/ScreenStream#149]
I have some doubts about modify and publishing this project on playstore.

Issues

https://github.com/dkrivoruchko/ScreenStream/issues/114

https://github.com/dkrivoruchko/ScreenStream/issues/141

you said that in issue 114  "You may do whatever you want but you have to keep full original MIT license (Including author name)."

![l2](https://user-images.githubusercontent.com/67687893/108338144-d7577700-71cd-11eb-8485-ba23c0712ff4.PNG)

But, in issue 141 you said that ,"no"

![playstore](https://user-images.githubusercontent.com/67687893/108338553-4c2ab100-71ce-11eb-89af-c2158ef08a86.PNG)

This project is very popular and also a powerfull tool for screen streaming purpose.

So , many developers want to modify and publish in playstore.

I want to add sound and touch feature to this app.

I heard this because I want to modify this app and publish on playstore with ads with including your MIT licence.

Can I have a permission for this ?

Can you give a detailed explanation about publishing ?

**Comment by dkrivoruchko** [comment]
Well, all current code as of today is under MIT license.
From legal point of view, there are no restrictions for anyone to do with this code whatever he/she wants (including creating app, publishing it, and making money).
Me personally doesn't like this as the initial idea is to give people free (including add-free) app with open sources so users be sure that there's data is not send to someone else.
It's ok when you use this project code in any your project, but I prefer such project to be nonprofit, with open sources, and keep reference to original ScreenStream project as a way of some respect of my (and other contributors) work and time.
