### ISSUE TITLE
Quick Settings Tiles

### ISSUE THREAD

**Issue by xmha97** [dkrivoruchko/ScreenStream#15]
Hi, Please Add Quick Settings Tiles in Android Nougat (like OpenVPN)

**Comment by dkrivoruchko** [comment]
What settings you want to see in tiles?

**Comment by mhd4mr** [comment]
https://i.imgur.com/IcUNDsz_d.jpg?maxwidth=640&shape=thumb&fidelity=medium 
In Android 7.0 you can add third party quick settings tiles

**Comment by dkrivoruchko** [comment]
Yes, i know.
The question was - what ScreenStream app settings you want to see as quick settings tiles?

**Comment by mhd4mr** [comment]
Start/Stop Streaming 
https://imgur.com/gallery/Cfo3R

**Comment by dkrivoruchko** [comment]
Ok. Thanks for idea.
