### ISSUE TITLE
Display touches on the screen

### ISSUE THREAD

**Issue by OmlineEditor** [dkrivoruchko/ScreenStream#155]
Is it possible to add the ability to show where the user touched his finger on the screen?
In the broadcast, it is not clear where the person is pressing, you need to show touches to improve perception.
---- RUS ----
Можно ли добавить возможность показывать где пользователь прикоснулся пальцем на экране?
В трансляции не понятно куда нажимает человек, нужно показывать прикосновения для улучшения восприятия.

**Comment by dkrivoruchko** [comment]
Only using Dev mode
Только используя режим разработчика

**Comment by OmlineEditor** [comment]
> Only using Dev mode
> Только используя режим разработчика

can you add this option to the program menu? not all users can enter developer mode.
--- RUS ---
вы можете добавить в меню программы эту опцию? не все пользователи могут войти в режим разработчика.

**Comment by OmlineEditor** [comment]
> This is technically not possible. User must go to settings and enable dev mode.
> And this is highly not recommended for users who don't understand what they are doing and what are the risks.

you do not understand, I am not asking to add a developer menu. I am asking you to add the ability to show finger taps to the menu of your program. This is by analogy with graphic programs that draw on the screen eyedroppers or circles in the form of an elastic band or any other element where the user touches.
---- RUS ----
вы не поняли, я не прошу добавить меню разработчика. я прошу добавить в меню вашей программы возможность показывать прикосновения пальца. Это по аналогии с графическими программами которые рисуют на экране пипетки или кружки в виде стительной резинки или любой другой элемент в месте прикосновения пользователя.

**Comment by dkrivoruchko** [comment]
I got you. In Android it's possible to do from Dev mode only.

**Comment by OmlineEditor** [comment]
> I got you. In Android it's possible to do from Dev mode only.

Okay, i understood, then the idea cannot be realized. the ticket can be closed

![okay](https://user-images.githubusercontent.com/13348933/111676226-08f44a00-882f-11eb-8718-5b2694b6fcb3.png)
