### ISSUE TITLE
backward interaction

### ISSUE THREAD

**Issue by OmlineEditor** [dkrivoruchko/ScreenStream#156]
Can I make a feedback? I want to help people and tell them what to press.
I watch the translation in the browser and click in the browser and the place where I click is shown on the phone. It just shows up without clicking.
--- RUS ----
Можно сделать обратную связь? Я хочу помогать людям и говорить что нужно нажимать.
Я смотрю странсляцию в браузере и нажимаю в браузере и на телефоне показывается место где я нажимаю. Просто показывается без нажатия.

**Comment by dkrivoruchko** [comment]
this is possible but I don't have time for this. PR appreciated.

**Comment by pggdt** [comment]
If you want to show the press movement, you coud try enable Developer options(by going to Setting > System > About phone, hit "Build number" 5 times) then turn on "Show taps". Then your tap would appear on screen. Looks like the round dot in the screenshot below
![index](https://user-images.githubusercontent.com/4413062/181210431-d2197457-c4ea-424c-a7f8-e5118b958818.jpg)
:

**Comment by OmlineEditor** [comment]
> If you want to show the press movement, you coud try enable Developer options(by going to Setting > System > About phone, hit "Build number" 5 times) then turn on "Show taps". Then your tap would appear on screen. Looks like the round dot in the screenshot below


No, that's not it. You don't understand what I want. I need to click remotely in my browser on my computer and these clicks should be visible on the phone screen

**Comment by dkrivoruchko** [comment]
Этого не в планах на ближайшее время

**Comment by OmlineEditor** [comment]
ну это же не значит что нужно закрывать тикет? Потом через пару лет и сделаете этот функционал, зачем тикет закрывать?
