### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by xmha97** [dkrivoruchko/ScreenStream#160]
Hi,
This app stream my screen in portrait (9:16)
I want to stream my screen in landscape (16:9)
Please help me.
![ScreenStream](https://user-images.githubusercontent.com/23485114/111891690-f3874780-8a09-11eb-9d0e-ccf0449737df.jpg)

**Comment by dkrivoruchko** [comment]
Just rotate your device screen.

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/111895994-b469ee00-8a2b-11eb-9a29-933eda33edcc.png)
![image](https://user-images.githubusercontent.com/23485114/111895995-baf86580-8a2b-11eb-9e4e-c25dbba8a9a5.png)
