### ISSUE TITLE
Task 'installDebug' not found in project ':app'.

### ISSUE THREAD

**Issue by stanlygamer** [dkrivoruchko/ScreenStream#164]
* What went wrong:
    Task 'installDebug' not found in project ':app'.

    * Try:
    Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug 
    option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 42s

When I build I have the following error. How can I solve this errror ?

**Comment by stanlygamer** [comment]
In this project :

![deb](https://user-images.githubusercontent.com/77946655/114165233-21362100-9924-11eb-8c27-821b9c122804.PNG)

new fresh android project:


![nd](https://user-images.githubusercontent.com/77946655/114165274-2c894c80-9924-11eb-85a3-80b31b2e2945.PNG)


you used installfirebasedebug  in this project.

but i didn't know any thing about this build.gradle configuration.

I am a student. I want to learn about this .

Why you used installfirebasedebug in this project ?

is installDebug  not work with this project ?

I need to change installfirebasedebug to installDebug How can I change build.gradle file for this configuration ?

**Comment by stanlygamer** [comment]
why you used firebase Implementation in this project ?

I need to change installfirebasedebug to installDebug How can I change build.gradle file for this configuration ?

**Comment by dkrivoruchko** [comment]
Use firebasefree build-varian.
And read about them https://developer.android.com/studio/build/build-variants

**Comment by stanlygamer** [comment]
I am using react-native . I integrate react-native with this project.  after integrating react-native with this project then  run 
 the  app but it comes an error like this

    * What went wrong:
    Task 'installDebug' not found in project ':app'.

    * Try:
    Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug 
    option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 42s


[this issue shows my problem.][1]


How can I solve this ?

  [1]: https://stackoverflow.com/questions/39119301/installdebug-not-found-in-root-project-android-react-native

**Comment by stanlygamer** [comment]
thanks for your replay!!!
