### ISSUE TITLE
Add support for

### ISSUE THREAD

**Issue by CyberBlueCodes** [dkrivoruchko/ScreenStream#166]
Please add support for Chat and Audio if possible, Thanks in advance. If it is not possible it's ok but please reply.

And can u teach me how to make all this stuff and how do u use local hosting on Android I thought u can only start it using CMD and which library did u use..

Please reply fast

            -CyberBlue

**Comment by dkrivoruchko** [comment]
App use MJPEG standard that has no audio support.
