### ISSUE TITLE
Stream over internet with ssh port forwarding

### ISSUE THREAD

**Issue by hummans** [dkrivoruchko/ScreenStream#168]
i have tried to use ssh port forwarding to get localhost port 8083 from an http server port 8088
But dosent work because the app port is used
cant start the app
im using JuiceSsh for port forwarding

is there any other option to get it from internet?
or can we use openvpn? i see only wlan ip
or can we stream directly to the server?
thnx

**Comment by dkrivoruchko** [comment]
Try Settings - Advanced in the app.
Remove "Use WiFi Only"

**Comment by hummans** [comment]
Ok solved with your support
finaly i was able to stream android over internet 
whith Openvpn and with an iptables rule on openvpn server:
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8083 -j DNAT --to 10.8.0.2          <--- ip of openvpn client

Thanks
