### ISSUE TITLE
Regarding supporting

### ISSUE THREAD

**Issue by pradeepkanna1234** [dkrivoruchko/ScreenStream#172]
Is screen stream is supported for all apps to stream .
Is every app is allowed for stream.

**Comment by dkrivoruchko** [comment]
This depends on app. If app sets https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE than system will not capture it's content

**Comment by pradeepkanna1234** [comment]
Is the third party app owner will know that the app is under going screen
streaming .

**Comment by dkrivoruchko** [comment]
I guess not.

**Comment by pradeepkanna1234** [comment]
Ok, thanks.

**Comment by pradeepkanna1234** [comment]
Sorry to disturb you again sir ,but please kindly answer this question
In online exam softwares can they find out us, that we are screening or
casting the question paper.And am attaching the screenshot of app allowance.
