### ISSUE TITLE
Feature Request: IP address modification

### ISSUE THREAD

**Issue by fgg1991** [dkrivoruchko/ScreenStream#186]
For android hotspot has frozen IP 192.168.43.1, the screenstream use this address for projecting either, would you consider to add a function to change not only port but the whole IP? Maybe like provide a fake IP for client to view the phone screen. Cause under some situation I found browser cannot visit 192.168.x.x IP page.

**Comment by dkrivoruchko** [comment]
App use what ever IP address device has. To change IP address in app - change device IP address. No other way
