### ISSUE TITLE
Feature suggestion: greyscale mode

### ISSUE THREAD

**Issue by zellyn** [dkrivoruchko/ScreenStream#192]
I have a [Boox Max Lumi 2](https://onyxboox.com/boox_maxlumi2), and ScreenStream works great. However, for some reason their drawing app uses color even though the screen only displays greyscale! So what looks light grey on the screen shows up as bright yellow when streaming!

It would be nice to stream what I'm actually seeing _and_ save bandwidth by streaming in greyscale only.

I'm happy to help work on this, if it's a feature you think would be worth adding.

**Comment by dkrivoruchko** [comment]
Hi. You can try to add this option to Settings-Image tab. Make a PR or wait when I have time to implement this.

**Comment by zellyn** [comment]
Thank you!
