### ISSUE TITLE
[enhancement]hide pin in settings->security when "hide pin when streaming" is enabled

### ISSUE THREAD

**Issue by mzltest** [dkrivoruchko/ScreenStream#198]
otherwise you will be able to see the pin in the stream even you choose to hide pin.
![97%R{GZVEBIPT`H{0II3}HJ](https://user-images.githubusercontent.com/52124882/171767063-c81e9f9d-9a70-4264-b4a2-896f9d2e30c1.png)
![F@_AO1EQ6 %2 )F@A5H}ZNK](https://user-images.githubusercontent.com/52124882/171767071-f62874d9-097f-433e-9589-b378c1935b4a.png)
the pin is "956941" here.

**Comment by dkrivoruchko** [comment]
Fided
