### ISSUE TITLE
remove Crashlytics

### ISSUE THREAD

**Issue by DJCrashdummy** [dkrivoruchko/ScreenStream#2]
is there a way to remove or replace Crashlytics?

it seems, this is the only issue what prevents ScreenStream to be included into fdroid-store:
https://gitlab.com/fdroid/rfp/issues/381#note_43347420

**Comment by dkrivoruchko** [comment]
Well, it's possible.
But it will be a separate brunch and builds different from app in Play Store

Dmitriy

**Comment by dkrivoruchko** [comment]
Done in brunch [Fabric-free](https://github.com/dkrivoruchko/ScreenStream/tree/fabric-free)
