### ISSUE TITLE
WebRTC Protocol

### ISSUE THREAD

**Issue by 2246sam20** [dkrivoruchko/ScreenStream#203]
is webrtc protocol beins used in this app?

**Comment by dkrivoruchko** [comment]
Currently, only MJPEG is used

**Comment by 2246sam20** [comment]
ok thanks !

**Comment by 2246sam20** [comment]
@dkrivoruchko  whats the protocol thats used  for streaming?

**Comment by dkrivoruchko** [comment]
Currently, only MJPEG is used
