### ISSUE TITLE
How can I access the frame from OpenCV?

### ISSUE THREAD

**Issue by Katana-O** [dkrivoruchko/ScreenStream#205]
I pasted my code here.

import cv2
#cap = cv2.VideoCapture('http://192.168.1.9:8080/')
cap = cv2.VideoCapture('http://192.168.1.9:8080/1')
#cap = cv2.VideoCapture('http://[::1]:8080')
while True:
    ret, frame = cap.read()
    cv2.imshow("frame", frame)
    key = cv2.waitKey(50)
    if key == 27:
        break
cv2.destroyAllWindows()

Here's the outcome I got.
![image](https://user-images.githubusercontent.com/79778115/190913644-a15641dc-243a-487b-9db8-6aabf020bf05.png)

**Comment by dkrivoruchko** [comment]
Well, I have no idea. But keep in mint that app use MJPEG and it's available http://192.168.1.9:8080/stream.mjpg
