### ISSUE TITLE
Possibility to backup the app config by ADB ?

### ISSUE THREAD

**Issue by Xenxia** [dkrivoruchko/ScreenStream#211]
Hello, 
Thank you for your application, it works very well.

I just have a small problem, it is to backup by the command 'adb backup'.
I tried to do it but the ".ab" file I get is empty.

Would it be possible to backup the config? or to find another way to configure the app remotely by another way? 

Thanks for your answer.

**Comment by dkrivoruchko** [comment]
Hi and thanks.
Backup is empty because it's disabled in app.
Why you need to configure app remotely?

**Comment by Xenxia** [comment]
Hello 

I'm trying to configure the app remotely without rooting the phone because I have an app that installs ScreenStream by ADB but I have no way to configure it to change for example (resizing, frame rate, etc ...) and also to disable the wifi to put in local host only because I make an "adb forward tcp:8080 tcp:8080" to my pc

If it is not possible by backup, is there any other way?

Thanks

**Comment by dkrivoruchko** [comment]
Ok. Looks like a very custom case. Let forget for a moment the technical part.
What will be an ideal functionality for you? Or what is a business case?
I prefer to add a functionality that is useful for many uses, not just for some particular case.

**Comment by Xenxia** [comment]
In a professional case I think of the installation and configuration of the app via usb without needing to perform the manipulation by hand on several devices.

I don't know if we can pass as argument a path of a config file when we launch the application via ADB

**Comment by dkrivoruchko** [comment]
Well, I see only one simple solution - enable config backup.
Most likely, it will appear in the next big 4.0 release.

**Comment by dkrivoruchko** [comment]
Ok. Try version 3.10.5

**Comment by Xenxia** [comment]
so I tried and it doesn't work 
`adb backup -all` returns very few apps and `info.dvkr.screenstream` is not in the backup

I did some research and I have the impression that it is necessary to root the device

I'm sorry to have wasted your time with this

I close the ticket

and thank you
