### ISSUE TITLE
Increasing font size on "/pinrequest" and "Press START on device" webpage

### ISSUE THREAD

**Issue by wqp53625** [dkrivoruchko/ScreenStream#224]
Hi @dkrivoruchko ,

Thanks a lot for this useful app.

The font size on the `/pinrequest` and _"Press START on device"_ webpages is somewhat small.

It would be appreciated if the font size would be increased.

Regards

**Comment by CeceliaBue1OR** [comment]
To increase the font size on the "/pinrequest" and "Press START on device" webpages, you can add CSS styles to the HTML code of the pages.
