### ISSUE TITLE
Toggling between Portrait and Landscape closes the stream

### ISSUE THREAD

**Issue by SMDIndomitable** [dkrivoruchko/ScreenStream#239]
Hi, I have two of the same phones but using different OS. The application works perfectly fine on Android Version 13. However on Android 14, the stream closes whenever the screen orientation changes. Is there any way I can get it working without closing the stream?

**Comment by dkrivoruchko** [comment]
Hi. Yes, this is expected behavior as in Android 14 a change was introduced https://developer.android.com/about/versions/14/behavior-changes-14#media-projection-consent

I'm searching for some workaround if possible.

**Comment by SMDIndomitable** [comment]
Understood, thank you for the information

**Comment by dkrivoruchko** [comment]
Fixed in 4.0.31
