### ISSUE TITLE
Removed Shortcut Tiles?

### ISSUE THREAD

**Issue by Streammet** [dkrivoruchko/ScreenStream#243]
I remeber that there where shortcut tiles for the Android tiles, but for me there are no longer avaible. I guess its a bug?

**Comment by dkrivoruchko** [comment]
Hi. It is not. It was removed, as there is no match reason to have it.
To start a stream, you now must always open an app itself because of permission request.

**Comment by Streammet** [comment]
For me it was just a natural thing to have it in the tiles, like the normal cast function would be. Is there any disadvantage in having it available?

**Comment by dkrivoruchko** [comment]
Ok, will try to add in some next release.

**Comment by dkrivoruchko** [comment]
Added in 4.1.1
