### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yuchen1204** [dkrivoruchko/ScreenStream#246]
Can you make the server source code public? Then allow users to fill in their own server IP on the client for global streaming (webRTC)

**Comment by dkrivoruchko** [comment]
Server code is public from the beginning: https://github.com/dkrivoruchko/ScreenStreamWeb

To run own server is not enough as app uses Play Integrity Library to make sure that only original verified apps can connect to the original server. This means that server has API keys for Play Integrity server API for this particular app and these keys are never been shared to public. 
So you can run your own server, but it will never accept requests from the original app.
And vice versa - original server will never accept connections from non-original app.
