### ISSUE TITLE
Android "Screen Cast Permission" Needed

### ISSUE THREAD

**Issue by Katsuyamaki** [dkrivoruchko/ScreenStream#247]
I cannot start the stream without enabling this permission. I cannot find a "Screen Cast" permission to enable in permission manager and screenstream doesn't have a popup to grant the permission.

How do I grant it?

![Screenshot_20240228-063306_ScreenStream](https://github.com/dkrivoruchko/ScreenStream/assets/142951417/2b207a77-eb1b-4c94-b344-a10e49de3c6c)

**Comment by dkrivoruchko** [comment]
Uninstall app and install it again.

**Comment by Katsuyamaki** [comment]
Update: It seems to potentially be a conflict with Shizuku. Without shizuku running (I use it for other apps) screenstream didn't give me that error.

Is there a way to have both running?

**Comment by dkrivoruchko** [comment]
ScreenStream has a VR mode. Maybe it helps
