### ISSUE TITLE
[Feature]Add Support for 120 fps

### ISSUE THREAD

**Issue by NpTIme** [dkrivoruchko/ScreenStream#254]
60hz is too slow for me =(

**Comment by dkrivoruchko** [comment]
You really think it can reach even 60Hz ?!

**Comment by NpTIme** [comment]
> You really think it can reach even 60Hz ?!

Yes actually... but with the resolution 540p

i just want to cast my android phone screen to the windows, but miracast does not work on my computer😥

**Comment by dkrivoruchko** [comment]
Ok, will add ability to set up 120Hz in the next version.

**Comment by dkrivoruchko** [comment]
Available from 4.1.5
