### ISSUE TITLE
Global mode throbber wheel

### ISSUE THREAD

**Issue by Thunderbone1982** [dkrivoruchko/ScreenStream#255]
When I try connecting to the StreamID on screenstream.io it will show on my phone app that a client is connected, but the web browser stalls out on the throbber wheel (loading symbol)
I've tried streaming via Wifi6, Cell phone Data 5g, and with or without VPN, same result.

**Comment by dkrivoruchko** [comment]
This is a network connection issue. But what exactly, it's hard to say. Try to open in browser a developer mode and check console. Maybe there will be some errors. Also, some ads filters may block WebRTC protocol

**Comment by dkrivoruchko** [comment]
Most likely TURN server required. Similar to #262
