### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by fdesjardins** [dkrivoruchko/ScreenStream#256]
Hi @dkrivoruchko, I really just wanted to say thanks for developing this. I've been fighting with screen sharing simulators for weeks for showing app progress for a client, and this app completely solved the problem. I was able to use the global option, share the link, and this app let me have a flawless demo of my work. On top of that, the app is free and MIT licensed. You're my hero today.

Is there a way I could sponsor this/you to at least buy you a coffee or something as a way to say thanks?

Also, do you know of a similar app for iOS? I know that seems to be out of scope for this project, but ScreenStream worked so well, it'd be amazing to have something like this for iOS. If not, no worries!

Thanks again!

**Comment by dkrivoruchko** [comment]
Hi and thanks. Currently, there is no way to support me. Sorry.
And I don't know any similar iOS app.
