### ISSUE TITLE
Is it possible to implement webp?

### ISSUE THREAD

**Issue by CristobalManga** [dkrivoruchko/ScreenStream#257]
I speak from ignorance, but I once read that the webp format compresses images very well.
This would cause the application to consume less bandwidth locally.
Is this possible?

**Comment by dkrivoruchko** [comment]
Well, You are not the first one who raised that question. There are two reason why there is no WebP in the app:
1. WebP compression is very slow (it requires much more calculation to produce smaller result) in comparison to JPEG. Meaning, if some device is capable to compress 20-30 JPEGs per second, the WebP will be around 2-3 per second.
2. App uses MJPEG standard to stream JPEGs, there is no such thing for WebP.
