### ISSUE TITLE
Translation Feature: Add translated data in strings.xml file.

### ISSUE THREAD

**Issue by SB2318** [dkrivoruchko/ScreenStream#258]
### Hello @dkrivoruchko,

**I'm interested in contributing to the translation. Could you please provide me with the names of the languages you are looking to translate into?**

**Comment by dkrivoruchko** [comment]
Hi. There is no exact list of languages. Just translate into the languages you know.
If you are a native speaker or know a language really well, then reviewing and/or improving existing translations is highly appreciated.

**Comment by SB2318** [comment]
> Hi. There is no exact list of languages. Just translate into the languages you know. If you are a native speaker or know a language really well, then reviewing and/or improving existing translations is highly appreciated.

Okay, Thanks for your response!
