### ISSUE TITLE
USB cable streaming

### ISSUE THREAD

**Issue by jkancel971** [dkrivoruchko/ScreenStream#26]
Hi. First of all: thanks for your very good work. I would like to know if there is a way to stream the android screen via USB cable? So if you don't have any Wifi or 4G available, you can just link the smartphone and your pc via an USB cable and then be able to stream your android screen? 
This would be really awesome. 
Thanks

**Comment by giantintheocean** [comment]
I found this app to be really nice in those regards. [Wired X Display](https://www.splashtop.com/wiredxdisplay) is compatible with Androids, Mac, Kindles, just about any OS. 

I don't think this app has the ability to from my experience at least.

**Comment by giantintheocean** [comment]
@jkancel971 I found this app to be really nice in those regards. [Wired X Display](https://www.splashtop.com/wiredxdisplay) is compatible with Androids, Mac, Kindles, just about any OS. 

I don't think this app has the ability to from my experience at least.

**Comment by dkrivoruchko** [comment]
Hi. Thanks for for all.
This app has no option or any way to stream via USB cable.
But there are many other apps that can do this, just search in Play Store.
