### ISSUE TITLE
App crashes on global mode on moto g84 5G

### ISSUE THREAD

**Issue by gaberilde** [dkrivoruchko/ScreenStream#260]
Hi i have a moto g84 5G with android 14 
I used to have android 13 but it still didn't work then either

When i start on global mode it says streaming and when i try to load stream app crashes and stream doesn't load

Any way of seeing if you can fix this issue?

**Comment by dkrivoruchko** [comment]
Please specify app version?

**Comment by gaberilde** [comment]
The latest which is 4.1.6 according to mine now

**Comment by dkrivoruchko** [comment]
Ok. Then please
1. go to about page.
2. Tap 5+ times on app version number
3. App will restart and enable logs collection.
4. Reproduce the issue.
5. Send logs to developer using button on top (has to be an email or any other way you like).
6. Disable logs in Settings - Genaral

**Comment by gaberilde** [comment]
[logs.zip](https://github.com/user-attachments/files/15969006/logs.zip)
I attached it here

**Comment by dkrivoruchko** [comment]
it's empty (

**Comment by gaberilde** [comment]
Yeah it won't send i think because it crashes the logs don't save

**Comment by dkrivoruchko** [comment]
Ok. Will try to find other way. Please wait

**Comment by dkrivoruchko** [comment]
Try 4.1.7

**Comment by gaberilde** [comment]
> Try 4.1.7

Still crashes, but acts a bit differently

When i press start stream now and click the link it just says

Waiting for host to start the stream

When i go back to the app to goes from stop back to start stream and when i click start again it crashes again 

Just noticed if i disconnect from site before pressing start again it doesn't crash anymore also only if i am viewing the site it crashes

**Comment by dkrivoruchko** [comment]
When you press start stream for the first time does app asks for screen capture permissions?

**Comment by gaberilde** [comment]
> When you press start stream for the first time does app asks for screen capture permissions?

You mean this box asking to start the screen?
![Screenshot_20240702-095135](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/857662d0-f0c9-4177-b3a6-286f9b5931df)
Yeah it asks once when i first press start then a 2nd time if i press it again after it stops then it crashes if i still have the site open when i click on start

**Comment by dkrivoruchko** [comment]
Looks like it's a crash in native WebRTC lib and there is no info about them in Crashlitics (

**Comment by dkrivoruchko** [comment]
If I make a test build for you to install and try, will you help me with testing?

**Comment by gaberilde** [comment]
> If I make a test build for you to install and try, will you help me with testing?

Sure

**Comment by dkrivoruchko** [comment]
Ok. Install it ant try to reproduce the issue. https://1drv.ms/u/s!AkPxCfD8XPiii_kFqWMRsKy5ZnknXg?e=g2y454
You can keep existing app from Play Store.

**Comment by gaberilde** [comment]
I get this trying to install it
![Screenshot_20240702-145013_1](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/9129edd0-9ff1-4a0d-8b0d-6e994f54df88)

**Comment by dkrivoruchko** [comment]
Strange. I can name only two reasons:
- File is corrupted. Thry to check it. SHA1 d0e9f82718dcdcd9da74dc8a84bf2ab3ad901704
- Your device might have security settings that prevent installation from unknown sources.

If the device is managed by an organization, then some restrictions can be endorsed.

**Comment by gaberilde** [comment]
> Strange. I can name only two reasons:
> 
> * File is corrupted. Thry to check it. SHA1 d0e9f82718dcdcd9da74dc8a84bf2ab3ad901704
> * Your device might have security settings that prevent installation from unknown sources.
> 
> If the device is managed by an organization, then some restrictions can be endorsed.

Nvm it was corrupted due to my crappy WiFi it's mine not a organizations also

![Screenshot_20240702-150429](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/319fccb6-d2cb-48b9-bc21-fc948b1bde63)

Says this now i guess i can't keep the play store version then either?
![Screenshot_20240702-150444](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/a92af3c6-f248-4e03-9ab7-7266c594ab9e)

**Comment by dkrivoruchko** [comment]
Ok, remove existing app first than.
But something is wrong here as it shouldn't compline about same package as they have different packages (

**Comment by gaberilde** [comment]
> Ok, remove existing app first than. But something is wrong here as it shouldn't compline about same package as they have different packages (

Done and it crashes in same way as the older play store version

**Comment by dkrivoruchko** [comment]
Yep., But now I have a crash logs in Crashlitics.
It crashes in native code with almost zero information (
`libc.so (Missing BuildId a9682a43d4afba2f7ad4dbb2a45a3a46)`
Will try to investigate.

Thanks for help.
You can remove this test version and install from Play Store.

**Comment by gaberilde** [comment]
> Yep., But now I have a crash logs in Crashlitics. It crashes in native code with almost zero information ( `libc.so (Missing BuildId a9682a43d4afba2f7ad4dbb2a45a3a46)` Will try to investigate.
> 
> Thanks for help. You can remove this test version and install from Play Store.

Yeah odd no worries il see what you can do

**Comment by dkrivoruchko** [comment]
Btw, what browser you use to connect to the stream?

**Comment by gaberilde** [comment]
> Btw, what browser you use to connect to the stream?

Might sound weird but it's kiwi browser and I'm trying to connect from the same phone maybe that doesn't help but i came here because some else couldn't connect to me either and i think they used chrome on phone also

**Comment by dkrivoruchko** [comment]
Can you please try to connect using chrome from some another device (phone, tablet, or PC). Using Play Store version.

**Comment by gaberilde** [comment]
> Can you please try to connect using chrome from some another device (phone, tablet, or PC). Using Play Store version.

Also crashes, immediately i also had the app screen open also

**Comment by dkrivoruchko** [comment]
Ok. Thanks

**Comment by dkrivoruchko** [comment]
Hi. Can you please try this version https://1drv.ms/u/s!AkPxCfD8XPiii_kPyOJ1FvH0SE8D4g?e=qOdJLF
It has the latest WebRTC native code.

**Comment by gaberilde** [comment]
Sure trying it now

**Comment by gaberilde** [comment]
Uhh
![Screenshot_20240705-093845](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/d4193e71-0503-4752-a768-0dbe3070e909)

**Comment by dkrivoruchko** [comment]
Oh, my! Try this one https://1drv.ms/u/s!AkPxCfD8XPiii_kR4hUkbvjHM5VhYg?e=FI1rEe

**Comment by gaberilde** [comment]
Now i just get this i even redownloaded and deleted the old one also
![Screenshot_20240705-095140](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/ed8098af-8f5b-46a3-b738-6c029067476d)

**Comment by dkrivoruchko** [comment]
Please check md5: be5fff4321e634b82e102abdd348754d6854af79

**Comment by gaberilde** [comment]
Yeah it does
![Screenshot_20240705-095649](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/c4b8a59b-71b3-4053-aae8-75c4d71aa9b2)

**Comment by dkrivoruchko** [comment]
Another attempt: https://1drv.ms/u/s!AkPxCfD8XPiii_kSWxrlx2Rmqwmt1g?e=2vvhne

**Comment by gaberilde** [comment]
Legend it actually works
![Screenshot_20240705-103049](https://github.com/dkrivoruchko/ScreenStream/assets/6341453/f1de0288-bf38-41f7-9b9e-e2ec377b2a8d)

**Comment by dkrivoruchko** [comment]
Well, that is good. Now I know what causes the issue. The challenge will be to bring a new version in to the app.
This may take a while.
Thanks for help.

Btw, in this test version audio dost work for some reason (

**Comment by gaberilde** [comment]
- ok no worries yea sorry didn't test audio

**Comment by dkrivoruchko** [comment]
Please recheck on 4.1.9 +
