### ISSUE TITLE
Sir, How to Stream Video with Audio?

### ISSUE THREAD

**Issue by arghya339** [dkrivoruchko/ScreenStream#263]

**Comment by dkrivoruchko** [comment]
1. Use WebRTC mode
2. Enable Mic and/or device audio
3. Start stream on device
4. Connect to stream from browser.
5. Turn on video volume in browser

**Comment by arghya339** [comment]
> 1. Use WebRTC mode
> 2. Enable Mic and/or device audio
> 3. Start stream on device
> 4. Connect to stream from browser.
> 5. Turn on video volume in browser

Sir, Video-Audio Stream possible in Local mode(without Cellular data)?

**Comment by KkRobin** [comment]
> 

ccfcd6092935b4437890566382112616f3dac5ca

**Comment by KkRobin** [comment]
>
