### ISSUE TITLE
stream mode webRTC

### ISSUE THREAD

**Issue by kun510** [dkrivoruchko/ScreenStream#264]
I can't find stream mode webRTC!!
![image](https://github.com/dkrivoruchko/ScreenStream/assets/89560519/34e7b60f-5494-4941-b839-d9904e5c3829)

**Comment by dkrivoruchko** [comment]
Where did you get this app version?

**Comment by kun510** [comment]
here : https://github.com/dkrivoruchko/ScreenStream

**Comment by dkrivoruchko** [comment]
Ok. Please read the App description in this repo:
`Google Play versions supports both Global mode (WebRTC) and Local mode (MJPEG) with ads included.
Versions from F-Droid, AAPKS are Ad-free and support only Local mode (MJPEG).`

**Comment by kun510** [comment]
So now how to use webRTC

**Comment by dkrivoruchko** [comment]
Remove existing application.
Install it for Google Play Store: https://play.google.com/store/apps/details?id=info.dvkr.screenstream

**Comment by kun510** [comment]
ok thank you!!
