### ISSUE TITLE
Lower refresh rate for eink devices

### ISSUE THREAD

**Issue by DwightNotFound** [dkrivoruchko/ScreenStream#272]
I'm streaming my phone to eink tablet, how can I manage  to get beyond 1fps, for example send 1 frame per 3 second as eink screen prefer static image. This helps me get a better battery life for both devices. 
Best regards.

**Comment by dkrivoruchko** [comment]
Hi.
I can try this, but don't expect significant battery improvement as image capture is managed by the system - once image is ready, app gets it. There is no way to manage this, the app can only drop the image.

**Comment by DwightNotFound** [comment]
Gracias! At least the display quality improves for eink screen as flickering reduces, I will test out the battery life.

**Comment by DwightNotFound** [comment]
Gracias! Sorry I messed up with github operation. Thank you for your attempt. At least display quality of eink screen improves as flickering reduces. I will test out the battery life.
