### ISSUE TITLE
[Feature Request] Will audio support be implemented for android 9?

### ISSUE THREAD

**Issue by Rypie109** [dkrivoruchko/ScreenStream#273]
I want to record a musical rhythm game on obs, but I recently found out that only android 10+ can stream audio + video at the same time. Is it a software thing with the version itself, or a thing with this app? I should mention I am talking about for global mode, on the play store version.

**Comment by dkrivoruchko** [comment]
Device audio is supported from Android 10 due to system limitations.
Prior to Android 10, the system does not have the necessary functionality to stream device audio.

**Comment by Rypie109** [comment]
Oh... That's a shame. Do you recommend anything? I really want to get this stuff working.

**Comment by Rypie109** [comment]
I managed to use windows 10 bluetooth audio receiver, along with local mode on this tool, and got everything working.
