### ISSUE TITLE
Trying to reconnect issue

### ISSUE THREAD

**Issue by nazima-mansoor** [dkrivoruchko/ScreenStream#278]
When I am trying to connect Local MJPEG screen share in multiple devices, it is showing **Trying to Reconnect** page in devices continuously. I am using stable network. In old module code it was working perfect in same network in multiple devices.

**Comment by nazima-mansoor** [comment]
While my screen share is going on, In another device showing shared screen in webview. But webview showing white screen only. Is there any idea about this ?

**Comment by dkrivoruchko** [comment]
WebView ussualy is a part of some app and has it's own configuration. 
Check WebView console for any errors. Probaly some WebView config issue
