### ISSUE TITLE
Screen split into multiple streams totaling entire screen

### ISSUE THREAD

**Issue by twoxfh** [dkrivoruchko/ScreenStream#28]
Feature request. Is it possible to split the screen into multiple streams totaling the entire screen? For example, I have a six inch eink reader and would like to stream my Android device to multiple 6 inch eink readers which are visually on top or side by side each other. Poor man's eink monitor.

Thanks for making this great app, and reading my crazy request.

**Comment by dkrivoruchko** [comment]
Well, it's possible to split image on android device before streaming and stream them to multiple devices.
But there is a technical problem with synchronization.
Currently (using MJPEG standard) there is no way to ensure proper image synchronization between multiple receivers. This will lead to the situation when some devices will show part from current frame and  some from previous (or even previous to previous).
So, sorry, but in current implementation with MJPEG it will not work.
