### ISSUE TITLE
Not supported on Quest devices

### ISSUE THREAD

**Issue by cgapk123** [dkrivoruchko/ScreenStream#280]
The global mode (WebRTC) cannot be used in the Quest3 VR device, and an error message will be prompted and the system will exit.

You can only install the local mode (MJPEG) mode, but there is no audio projection in this mode

![image](https://github.com/user-attachments/assets/05085785-3499-48a7-a559-a3c9a89004d1)

**Comment by dkrivoruchko** [comment]
Global mode (WebRTC) requires Google Play Services on device.

**Comment by cgapk123** [comment]
> Global mode (WebRTC) requires Google Play Services on device.

Is it possible to update Local Mode (MJPEG) to support audio transfer?

This github project contains Global Mode (WebRTC) and Local Mode (MJPEG), I just need the github source code for Local Mode (MJPEG) only, what should I do?

**Comment by dkrivoruchko** [comment]
MJPEG standard has no audio support, so no (

**Comment by dkrivoruchko** [comment]
I don't know )
