### ISSUE TITLE
[Feature request] RTSP Protocol

### ISSUE THREAD

**Issue by ClockGen** [dkrivoruchko/ScreenStream#3]
Is it possible to add support for RTSP protocol? 
Right now it's possible to access stream file (stream.mjpeg) from OBS on the same network and stream (via rtsp) from there.
Thanks for this amazing app.

**Comment by dkrivoruchko** [comment]
Hi!.
Interesting Idea.
I'll research it.
Thanks.
Dmitriy

**Comment by ClockGen** [comment]
Oh, sorry for confusion, I meant RTMP protocol (the one used for streaming to services like twitch, picarto, etc).

**Comment by dkrivoruchko** [comment]
Sorry, but NO
Dmitriy

**Comment by ClockGen** [comment]
I see, thanks for the information.
