### ISSUE TITLE
Continuously crashing on Samsung S7

### ISSUE THREAD

**Issue by mikini** [dkrivoruchko/ScreenStream#33]
V1.8.8 [from f-droid](https://f-droid.org/en/packages/com.orpheusdroid.screenrecorder/) crashes immediately on startup on my Samsung S7 (SM-G930F). Earlier version did the same (unknown version ).
Could try to get some logs from adb if necessary. 

![tmp_25204-screenshot_20181030-171726_samsung experience home2302914340036700698](https://user-images.githubusercontent.com/1330166/47733030-558b5a80-dc5f-11e8-92c8-e2e7031720b4.jpg)

![tmp_25204-screenshot_20181030-171341_f-droid8643980969194593022](https://user-images.githubusercontent.com/1330166/47733068-64720d00-dc5f-11e8-9971-8b66f2d11901.jpg)

![tmp_25204-screenshot_20181030-170953_settings5560936531414099937](https://user-images.githubusercontent.com/1330166/47733094-6f2ca200-dc5f-11e8-8589-70df7dda4625.jpg)

**Comment by dkrivoruchko** [comment]
Use version 2.2.1 [ScreenStream-fabricfree.apk](https://github.com/dkrivoruchko/ScreenStream/releases/download/2.2.1/ScreenStream-fabricfree.apk)
