### ISSUE TITLE
Permissions request

### ISSUE THREAD

**Issue by cl3wis** [dkrivoruchko/ScreenStream#37]
I am installing v2.15 from F-Droid on an Moto G5 Plus running Android 8.10. When installing the application, the permission screen says "This application does not require any special permissions". When running the app after installation, pressing "Start Stream" shows a dialog box reading "Screen Stream will start capturing everything that's displayed on your screen." I am unable to proceed by tapping the "start now" button. If I tap "cancel", a dialog reading "Application requires Screen Cast permission to capture screen."

**Comment by LBegnaud** [comment]
I'm running into the same situation here on pixel 2xl running android 10. 

I'm coming up with nothing googleing "cast permission" for android.

**Comment by dkrivoruchko** [comment]
[MediaProjectionManager.createScreenCaptureIntent](https://developer.android.com/reference/android/media/projection/MediaProjectionManager.html#createScreenCaptureIntent()) Returns an Intent that must be passed to startActivityForResult() in order to start screen capture. The activity will prompt the user whether to allow screen capture.

**Comment by LBegnaud** [comment]
I'm getting a popup asking to allow screen cast, when I hit "start", the red icon shows up near the clock, but quickly vanishes

**Comment by dkrivoruchko** [comment]
Yes. this is a correct behavior.

**Comment by LBegnaud** [comment]
but... streaming doesn't work. Perhaps I'm missing something crucial here?

 - I set the app to require a PIN
 - start streaming
 - load web interface
 - enter PIN
 - streaming stops and red icon near clock disappears

Edit: Just tried it again and it works now... Only thing i can guess happened is some time passed? Really strange. Thanks for entertaining my apparently ignorant questions.
