### ISSUE TITLE
HTML buttons to host keyboard buttons feature?

### ISSUE THREAD

**Issue by twoxfh** [dkrivoruchko/ScreenStream#4]
I am using this app to display Google books on my eink reader, any chance of page up and down buttons on the webpage that invoke keyboard strokes on host device would be appreciated. This would allow me to navigate the book without holding the phone. YouTube is jittery but works enough for me. Great work.

**Comment by dkrivoruchko** [comment]
You want to have buttons on Web Page that loads from phone and by pressing this buttons ScreenStream app invoke keyboard strokes on phone?

**Comment by twoxfh** [comment]
Exactly. That would be very helpful.

**Comment by dkrivoruchko** [comment]
I'll try to explore if this can be implemented.

**Comment by twoxfh** [comment]
Thanks, I appreciate it. If helpful I can put together a video of this usecase.

**Comment by dkrivoruchko** [comment]
If you have time

**Comment by java-py-c-cpp-js** [comment]
It's a very good idea to have the possibility to send keyboard input. But why only use buttons on webpage? You could use the real keybord of the computer viewing the website, too (except special keys that are catched by the web browser).

**Comment by dkrivoruchko** [comment]
Well I don't know any official way in Android to manage one app from another.
This is a basic Android security feature - isolate apps.
So if any one know a way to do this - please let me know.

**Comment by digitalcircuit** [comment]
There's a way to inject key events by creating a virtual/software keyboard, and there's an open-source project for this: [WiFi Keyboard (F-Droid)](https://f-droid.org/packages/com.volosyukivan/ ), [source on GitHub](https://github.com/ivanvolosyuk/wifikeyboard ).  Works without root, though is a slight hassle to enable.

One could just use WiFi Keyboard in a separate browser window, arranging the two so WiFi Keyboard has focus while ScreenStream remains visible, though it's not as nicely integrated.
