### ISSUE TITLE
app starts automatically after boot (since version 3.x)

### ISSUE THREAD

**Issue by DJCrashdummy** [dkrivoruchko/ScreenStream#40]
since 3.x somehow the app starts itself (thankfully not the stream) after booting the device. - initially i thought it was a bug, because i had _"Start on boot"_ unchecked.

this is somehow annoying if you just use the app occasionally and is IMHO still a bug. there should rather be a checkbox like _"Start **stream** on boot"_ for _"Start **app** on boot"_. is this possible to add?

---

btw: changing the items _"Start on boot"_ and _"Stop on sleep"_ to _"Start **stream** on boot"_ and _"Stop **stream** on sleep"_ would clarify things anyway.

**Comment by dkrivoruchko** [comment]
Actually app ALWAYS starts after device boot to check whether it need to start stream.
If there is no need to start stream - app should closed by itself.
I'll check if there are some issues with this. Can you enable logs in app, then reboot device, then WAIT for app starts by itself and then send me app logs?
But for the time been it's the first such issue reported.
P.S. Thanks for name improvement idea. Will change in 3.0.8

**Comment by dkrivoruchko** [comment]
I confirm bug with start on boot option.
Fixed in 3.0.8

**Comment by DJCrashdummy** [comment]
thanks for investigating (and fixing) this bug!

@dkrivoruchko do you still want a log, or should i just wait and check the fix with 3.0.8 release?

**Comment by dkrivoruchko** [comment]
No log needed. Just Wait for 3.0.8
