### ISSUE TITLE
Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by RameshbabuJaga** [dkrivoruchko/ScreenStream#42]
I have tried importing and run your project and  got this issue.

Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
 got this error. https://developer.android.com/studio/build/dependencies#duplicate_classes.   

I have tried excluding this ResultReceiver module and no luck same error. Below is the part i tried.

implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion"){
        exclude group: 'android.support.v4.os', module: 'ResultReceiver'
    }

I have also searched the [stackoverflow](https://stackoverflow.com/questions/50387207/error-while-merging-dex-program-type-already-present-android-support-v4-os-resu) and found that mixing of old and androidx causing this problem. 

Any help

**Comment by RameshbabuJaga** [comment]
Ok. Do i want to add this 
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion"){
exclude group: 'android.support.v4.os', module: 'ResultReceiver'
}

**Comment by dkrivoruchko** [comment]
no, you don't need this

**Comment by dkrivoruchko** [comment]
In your gradle.properties add
android.useAndroidX=true
android.enableJetifier=true

**Comment by RameshbabuJaga** [comment]
Yeah i have added the above mentioned properties. No luck new error. will post here shortly

**Comment by RameshbabuJaga** [comment]
Yeah thanks. Above properties resolved the issue. Thanks for the wonderful project.

**Comment by dkrivoruchko** [comment]
Super. Thanks

**Comment by mikequic** [comment]
Excuse my ignorance, but do you mean "gradle-wrapper.properties".  I don't see a "gradle.properties" file. I've added those 2 lines to gradle-wrapper.properties and I still get the error.

**Comment by dkrivoruchko** [comment]
No.
First - revert "gradle-wrapper.properties" to it's original state.
Second - "gradle.properties" does not included to this repo. When you clone this project and open in Android Studio - then in root folder should be "gradle.properties"

**Comment by mikequic** [comment]
Thank you. I ended up with a "local.properties" file.  I copied to "gradle.properties" and added the lines. Then it worked.

**Comment by Riyaz0001** [comment]
I am already solved this problem: https://stackoverflow.com/questions/50676100/program-type-already-present-android-support-v4-os-resultreceivermyresultrecei/55345901#55345901
