### ISSUE TITLE
Can't compile application

### ISSUE THREAD

**Issue by Nikonov** [dkrivoruchko/ScreenStream#46]
Dear Dmitriy,

Can't compile last version application. I have error: Error: Program type already present: android.support.v4.os.ResultReceiver

Android Studio: 3.3
ScreenStream application: 3.0.10

Could you please help?

**Comment by dkrivoruchko** [comment]
Duplicate #42

**Comment by dkrivoruchko** [comment]
In your gradle.properties add
android.useAndroidX=true
android.enableJetifier=true
