### ISSUE TITLE
IP forward not working while running on Emulator / simulator

### ISSUE THREAD

**Issue by hussulinux** [dkrivoruchko/ScreenStream#47]
I'm trying to run it on the emulator and after all port forwarding and stuff, it wont forward the http page. 
Note : I'm not using wifi, but rather ADB's built in router to give me a private IP:port. 
This private IP:port is displayed on emulator screen, but its not accessible via host computer's browser. 
I've setup portforwarding via ADB. ( Note: My other apps portfowardings are working fine, so port forwarding definitely is working for other apps )
Does it have to do something with loopback where it binds to? if so, Where can I correct it ?

**Comment by dkrivoruchko** [comment]
Server starts on all device IP addresses [Code](https://github.com/dkrivoruchko/ScreenStream/blob/22f104229fe879dd3633228f2751ebe44656c05b/data/src/main/kotlin/info/dvkr/screenstream/data/httpserver/AppHttpServerImpl.kt#L70).
But it will reply only on request to discovered IP addresses (Address you see in app) [Code](https://github.com/dkrivoruchko/ScreenStream/blob/22f104229fe879dd3633228f2751ebe44656c05b/data/src/main/kotlin/info/dvkr/screenstream/data/httpserver/HttpServerRxHandler.kt#L80)
