### ISSUE TITLE
Still image Jpg

### ISSUE THREAD

**Issue by sdesalve** [dkrivoruchko/ScreenStream#58]
Hi, 

Is there a way to obtain a jpg still image?
Do you plan to add this functionality on next future?
I want to add screen streaming to my HomeAssistant and I need also a jpg source URL

Cheers

**Comment by dkrivoruchko** [comment]
What do you mean by jpg still image?
App send a stream of jpeg images already using MJPEG standard.

**Comment by sdesalve** [comment]
Another URL address that serve a jpg image.
Obiuvsly image should refresh at each page load

**Comment by dkrivoruchko** [comment]
if you do not use pin in app try this http://192.168.1.1:8080/stream.mjpeg
use your ip address from app instead "192.168.1.1:8080"

**Comment by sdesalve** [comment]
Like stated in Hassio's Docs (https://www.home-assistant.io/components/mjpeg/) an your suggestions, I've tried with

```
camera:
  - name: "Tablet mjpeg"
    platform: mjpeg
    still_image_url: "http://192.168.1.149:8080/stream.mjpeg"
    mjpeg_url: "http://192.168.1.149:8080/stream.mjpeg"
    verify_ssl: false
```
But don't work. I get this error on homeassistant.log: 
`2019-06-03 16:50:56 ERROR (MainThread) [homeassistant.components.mjpeg.camera] Timeout getting camera image` 
and no snapshot preview in GUI.


I've tried to make a snapshot with ffmpeg:

ffmpeg -f MJPEG -y -i http://192.168.1.149:8080/stream.mjpeg -r 1 -vframes 1 -q:v 1 $folder/tablet_screen_$id.jpg

but I'm getting this error:

`+ ffmpeg -f MJPEG -y -i http://192.168.1.149:8080/stream.mjpeg -r 1 -vframes 1 -q:v 1 /config/www/temp/tablet_screen_19-06-03_16-38-35.jpg
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.0 (Alpine 8.2.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-asm --disable-debug
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mjpeg, from 'http://192.168.1.149:8080/stream.mjpeg':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 640x400 [SAR 1:1 DAR 8:5], 25 tbr, 1200k tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/config/www/temp/tablet_screen_19-06-03_16-38-35.jpg':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 640x400 [SAR 1:1 DAR 8:5], q=2-31, 200 kb/s, 1 fps, 1 tbn, 1 tbc
    Metadata:
      encoder         : Lavc58.18.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
/config/ffmpeg/snapshot_tablet.sh: line 7:    68 Segmentation fault      (core dumped) ffmpeg -f MJPEG -y -i http://192.168.1.149:8080/stream.mjpeg -r 1 -vframes 1 -q:v 1 $folder/tablet_screen_$id.jpg
`

Can you add a JPG still image endpoint? Or can someone suggest me how make ffmpeg works with your app's MJpeg stream?

Thank you

**Comment by dkrivoruchko** [comment]
Well, it works for me. You have to start stream on device before running command.
```d:\ffmpeg-20190603-0b7bfa8-win64-static\bin>ffmpeg -f MJPEG -y -i http://192.168.231.86:8080/stream.mjpeg -r 1 -vframes 1 -q:v 1 s.jpg
ffmpeg version N-93981-g0b7bfa8ad7 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 52.102 / 58. 52.102
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, mjpeg, from 'http://192.168.231.86:8080/stream.mjpeg':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 540x1170 [SAR 1:1 DAR 6:13], 25 tbr, 1200k tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, image2, to 's.jpg':
  Metadata:
    encoder         : Lavf58.27.103
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 540x1170 [SAR 1:1 DAR 6:13], q=2-31, 200 kb/s, 1 fps, 1 tbn, 1 tbc
    Metadata:
      encoder         : Lavc58.52.102 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    1 fps=0.0 q=1.0 Lsize=N/A time=00:00:01.00 bitrate=N/A speed=41.8x
video:49kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

d:\ffmpeg-20190603-0b7bfa8-win64-static\bin>```
