### ISSUE TITLE
permission..

### ISSUE THREAD

**Issue by erqan** [dkrivoruchko/ScreenStream#59]
with version 3.1.7 on android 9 (oneplus 5) after pressing start, nothing happens, ui freezes and after pressing back button, it says "ScreenStream application requires Screen Cast permission to capture screen"
![Screenshot_20190620-124106](https://user-images.githubusercontent.com/12120467/59841408-f2207b00-935c-11e9-9296-33326f3ddcdf.jpg)

**Comment by dkrivoruchko** [comment]
Remove and install app. Try to start.

**Comment by erqan** [comment]
i have tried, same...

**Comment by dkrivoruchko** [comment]
I have android 9 (oneplus 6T) no issues.
Go to app settings - advanced - enable app logs.
try to start and send logs pls

**Comment by erqan** [comment]
i don't know why but it can't display ```com.android.systemui/.media.MediaProjectionPermisionActivity``` and i've noticed that issue doesn't affect only the ScreenStream app, it's common issue for MediaProjection api in my device, i think something is wrong with my installation. sorry for any inconvenience.
