### ISSUE TITLE
[FR] Camera support

### ISSUE THREAD

**Issue by CrimsonFork** [dkrivoruchko/ScreenStream#6]
It would be nice if one could run one/both cameras alongside/instead of the screen capture.

**Comment by dkrivoruchko** [comment]
Well you can do this by opening camera preview in any camera app.

**Comment by OffifialMITX** [comment]
Yes, but it would be covered with camera's UI and one wouldn't be able to lock the phone without having to stop the stream, which results in a much higher power consumption that it would be with a built in option.

**Comment by dkrivoruchko** [comment]
Good point. I'll think about it.

**Comment by dragetd** [comment]
As far as I am aware, Android does prevent applications from taking pictures without showing a preview. At least streaming from the camera needs a preview, tho this can be resized to 1x1px.

Taking a picture from a background service on a locked phone comes with a lot of challenges, including powersaving/dowse also not happy about a backgroundservice hogging CPU.

Some apps avoid the whole issue with root and directly accessing the camera.

I would also love to have this very elegant and easy way of exporting the cameras via web… but might be a tough nut to crack. :(

**Comment by dkrivoruchko** [comment]
I'm definitely will not use any root-required functionality

**Comment by treakiandroid** [comment]
Thers still an app for that, see MobileWebCam (Simple webcam) - https://f-droid.org/app/com.dngames.mobilewebcam

The only problem is that it takes fotos from the androis interface and not a video stream, so even much lower (mostly do to the api request which includes one autofocus measurement and much more). Also it saves all images to the sdcard so you have to cleare them to don't run out of space quickly. And the app design is quite old, so building in a frwture in this modern app would be not a bad idea but check that old thing out bedore, maybe its enough...

**Comment by Bibi56** [comment]
Another option is to use CamCov with an alpha value of 1.
It makes the UI almost invisible, you can create a black screen and then that's it.
As it's open source you may be able to integrate it a better way.
