### ISSUE TITLE
How to add new translation

### ISSUE THREAD

**Issue by tiborepcek** [dkrivoruchko/ScreenStream#66]
Hi, i would like to know, which files to translate into new language and which are the source files?

And it would be nice to add this info to readme.md IMHO.

Thank you. :)

**Comment by dkrivoruchko** [comment]
You have to translate this
https://github.com/dkrivoruchko/ScreenStream/blob/master/app/src/main/res/values/strings.xml
and this
https://github.com/dkrivoruchko/ScreenStream/blob/master/data/src/main/res/values/strings.xml
