### ISSUE TITLE
Encryption and password protection

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [dkrivoruchko/ScreenStream#7]
Would it be possible to add an option for https/ssl and password protection? This would leed to more security, for example on public WLAN. Because it would has to use self signed zertificates, the hash sum, fingerprint or something like that could be displayed in the app to compare it with the information from webbrowsers like firefox to prevent man-in-the-midfle attacks.

**Comment by java-py-c-cpp-js** [comment]
Sorry, I don't recognised that a pin protection is already implemented.

**Comment by dkrivoruchko** [comment]
Well, current solution with pin is a very basic security option.
And i think it's enough, because app allow only viewing not managing android device.
Regarding https/tls. It it not a good option because of two points:
1. Android device have to have static real ip address and public resolvable dns name. Which is obviously not a common case for mobile device.
2. Any ssl/tls on device will require additional CPU resources to encrypt/decrypt traffic while it is already heavy loaded with continuous image compression and some app user actually displaying. 

So no https will be provided.

**Comment by Echolon** [comment]
Hello,

Firstly, I'd like to provide some extra information about the additional loads of HTTPS: https://istlsfastyet.com/     According to this, the loads are not that significant before.

Furthermore, to share my screen still provides sensitive information depending what you are doing. I still like to encourage to implement an encrypted connection.

And how does other clients mange the static ip issue and provide HTTPS?

Thank you anyway for your app!

**Comment by dkrivoruchko** [comment]
You are right that TLS has smapp performance impact. But this is mostly true for big servers and network equipment, not for mobile devices. Yes, some mobile cpu has hardware tls/ssl offload engine to speed up encryption process, but I have no idea how to use them in custom/third party (non system) app.

The problem with static IP and domain name usually solved with adding in to problem an external proxy server with static IP/Domain name with running an HTTPS server on it. Then app connect to this server via https and send all data to it. Clients connect also to this external server via https and get the data.

To build such is one of my next goals. But i'm not a web server developer, yet )

Also there are many issues that have to be solves for such poxy solution.
1. This server has bo be an open source project so people may check that there data/stream is not copied to someone else.
2. To ensure security the best way for users is to run a private instance of such server on there own hardware. But not all users has enough experience and/or time to do this.
3. So some public instance has to be running somewhere in internet to use it with app from Play Store. This will cost some money. Currently app is my nonprofit free time project. If  I add a functionality for external server to app in Play Store, then I have to run anu pay for this server and will not be free.

P.S. This is an open project. If someone what to help me with server part this will be nice.
