### ISSUE TITLE
Not working with different network

### ISSUE THREAD

**Issue by dhalloop7** [dkrivoruchko/ScreenStream#70]
I tried to stream the screen over the internet. It's working with only the same network but when I tried with mobile data to stream in my desktop with WiFi network it's not streaming. It's giving a black screen only.

**Comment by dkrivoruchko** [comment]
Please read app description:
WARNING: Some cell operators may block incoming connections to your device for security reasons, so, even if the device has an IP address from a cell operator, you may not be able to connect to the device on this IP address.
WARNING: Some WiFi networks (mostly public/guest) block connections between its clients for security reasons, so you may not be able to connect to the device via WiFi. For example, a laptop and a phone in this such a WiFi network will not be able to connect to each other.

In general case - network has to provide and allow network connection from client (Web-browser) to device with running app on it.

**Comment by keshav12-36** [comment]
> I tried to stream the screen over the internet. It's working with only the same network but when I tried with mobile data to stream in my desktop with WiFi network it's not streaming. It's giving a black screen only.

Use portforwarding with ngrok

**Comment by keshav12-36** [comment]
.
