### ISSUE TITLE
[Feature Request ?!?] It could be posible to insert this app into another one?

### ISSUE THREAD

**Issue by GuillermoDoradoVide** [dkrivoruchko/ScreenStream#76]
Hi, I really like your app! 
I'm testing launching it by code while in another app. It opens your app within the other app and its very handy (sort of).
But it could be very cool if with a press of a button on another app it could launch and start the stream directly (without changing apps).
I don't know if its posible or allowed, so...

Nevertheless, great work!

**Comment by dkrivoruchko** [comment]
What do you mean by changing apps?

**Comment by GuillermoDoradoVide** [comment]
Without having to pause my app to open yours, start the stream, and then return to my app again.
Like, including a button on my app that launches directly the streaming service.

**Comment by dkrivoruchko** [comment]
Well, in any case use has to confirm permission request and it has to be done withing the app. So no.
