### ISSUE TITLE
[Feature request] borderless casting

### ISSUE THREAD

**Issue by mselmanyildirim** [dkrivoruchko/ScreenStream#80]
Thanks for this useful application. I've been using for a long time with pleasure.
A feature that may be easy to implement, imho:
Is it possible to cast the video without borders around the video? I mean the background border, which we can choose its color. It would be good if we can remove it to use maximum screen space in browser window.
Thanks again for your efforts!

**Comment by dkrivoruchko** [comment]
Well, if screens aspect ratio is the same - the will be no additional borders.
Otherwise there always will be some additional border

**Comment by mselmanyildirim** [comment]
If you still have a border in landscape (which was in my case), check whether image resizing is enabled. The image may be too small to fill the screen after resizing. Just disable resizing (adjust to 100).

Seems obvious, but took me too long to figure out.
