### ISSUE TITLE
Using Smart View with this app

### ISSUE THREAD

**Issue by neeloor** [dkrivoruchko/ScreenStream#81]
With Samsung "Smart View" I can mirror my phone screen to TV. But if I start "Smart View" while "Screen Stream over HTTP" is running, it disconnect. is it possible to use both together ??

Thanks

**Comment by dkrivoruchko** [comment]
Try in app settings set different port like 8088

**Comment by neeloor** [comment]
Thanks for the reply, but it did not work , is there any way to share video buffer between to apps ??

**Comment by dkrivoruchko** [comment]
I don't know any (
