### ISSUE TITLE
better default values = better (first) impression of the app

### ISSUE THREAD

**Issue by DJCrashdummy** [dkrivoruchko/ScreenStream#84]
*i also wanted to fix or at least report https://github.com/dkrivoruchko/ScreenStream/commit/263b452546fd3f49aba2e8cbe79a940dfdabea56 today... but nice that it is already fixed! :+1: - so straight to my second point...*

- - -

as ScreenStream is not intended for high-quality-streaming, what do you think about lowering the default jpeg-quality, because 50% or also 40% still looks pretty ok to me. (80% is used in most digi-cams for pictures!)
in the same course i would raise the default picture rate... perhaps round about double it to something like 15-20.

so the user will get a slightly worse picture quality but a far less laggier experience... and over all this will result IMHO in a much better (first) impression for users who don't fiddle around with the settings (which is by far the vast majority).

**Comment by dkrivoruchko** [comment]
Thanks for ideas, default frame rate is also increased to 30 FPS.
Will look at picture quality. The biggest concern - better compression - more delay. But I'm unsure about that. some research required.
