### ISSUE TITLE
[Feature Request] Floating button to toggle "play/pause"?

### ISSUE THREAD

**Issue by vikrant123pundir** [dkrivoruchko/ScreenStream#85]
Keeping in mind that app opens on using notification button due to Android limitation, please add a small semi-transparent on-screen floating button to play/pause streaming.
From a teacher's perspective, I can't let my students attention to go anywhere else while I Google images, meanwhile my phone's screen being projected.
That will allow the user to pause, then search images another tab, and start streaming again when I find the correct image to be presented & teach any of their questions.
And yes, please add a "Donate" link in about section. This application is really helping me a lot.

**Comment by dkrivoruchko** [comment]
There is a Tile for this - just add it to the top list. [Tile example](https://github.com/dkrivoruchko/ScreenStream/raw/master/screenshots/screenshot_12.png)
I'd like to add "Donate", but I can't - Google Policy
