### ISSUE TITLE
v3.4.4-5 size

### ISSUE THREAD

**Issue by Rikk** [dkrivoruchko/ScreenStream#86]
Hi, was the size increment of this new version caused by this Ktor thing? If so, what improvements does it bring to the app?

My phone always lack free space, therefore I don't like when an app grows a lot in a single jump.

Fabricfree numbers:

| | |
| --: | -- |
| apk | 2.60 » 3.49 MB |
| dalvik-cache | 7.16 » 13.73 MB |

**Comment by dkrivoruchko** [comment]
Yes, this is Ktor (Ktor + Netty).  I was intended to move to Ktor + CIO (with expect to be smaller then Netty + Rx in < 3.4.4), but CIO has critical bugs for now.
And Ktor require [Java 8 desugaring on Android](https://developer.android.com/studio/preview/features#j8-desugar) witch may also increase apk size. 
Bottom line - for your case I suggest to use 3.3.2 as the most stable now.
