### ISSUE TITLE
Cannot insert values > 99 in Resize Image Dialog

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [dkrivoruchko/ScreenStream#9]
In the resize image dialog it's not possible to inset numbers with more than 2 digits althougt it promise values between 10 and 150 are possible. I'm using the version from FDroid.

**Comment by dkrivoruchko** [comment]
This is already fixed in 2.1.5.
It's available om Play Store and in releases [2.1.5](https://github.com/dkrivoruchko/ScreenStream/releases/tag/2.1.5)

**Comment by JobLeonard** [comment]
I guess F-droid takes a few days to pull in the updates?

**Comment by dkrivoruchko** [comment]
I have no idea. I don't push update to F-Droid

**Comment by JobLeonard** [comment]
Do you mean you didn't push the update there, or that someone else is responsible for the F-droid builds?

Thanks for making a great app, btw, I just (briefly) installed the play store version to leave a positive review :)
