### ISSUE TITLE
Feature request: setting to only allow connections from localhost

### ISSUE THREAD

**Issue by sudomain** [dkrivoruchko/ScreenStream#93]
It might seem like an extreme edge case, but it would be useful to have a setting to only allow connections from localhost. I use Termux which has an SSH package complete with port forwarding. There are a couple ways I'd be able utilize local and remote port forwarding to access the ScreenStream port, but I'd really like to be able to restrict the number of devices with access (beyond the 4 digit pin)

**Comment by dkrivoruchko** [comment]
Will think about it

**Comment by arash1999** [comment]
[]() toofan967@gmail.com. for connecting to TV Samsung 46inch series 7

**Comment by sudomain** [comment]
@dkrivoruchko I think I can give this a try using what I've learned about the advanced settings editor.  Pleaze let me know what you think of my proposed changes:

1. a change to advanced settings with the following checkboxes:
`
[ ] Use WiFi
[ ] Use Cellular Data
[ ] Use Loopback interface
[ ] Enable ipv6
[ ] Server Port
`
Removing "Only" from the Wifi option and adding a Cellular Data option would simplify the logic needed since loopback/localhost is an interface on it's own. Does this work with what you have planned for the app?

2. Also the 'advanced' tab could probably be renamed to 'interface', while the current 'interface' tab could be renamed to 'appearance' since it mainly has to do with the appearance of the app.

**Comment by dkrivoruchko** [comment]
Thanks for proposal, @sudomain but I almost complete it myself. So, tanks for help. Soon will be in production.
