### ISSUE TITLE
HttpServerNioLoopProvider.kt at line 18 NioEventLoopGroup param is not right

### ISSUE THREAD

**Issue by lovederh** [dkrivoruchko/ScreenStream#95]
e: /Users/lee/study/ScreenStream/data/src/main/kotlin/info/dvkr/screenstream/data/httpserver/HttpServerNioLoopProvider.kt: (18, 21): None of the following functions can be called with the arguments supplied: 
public constructor NioEventLoopGroup(p0: Int, p1: ((Runnable!) -> Unit)!) defined in io.netty.channel.nio.NioEventLoopGroup
public constructor NioEventLoopGroup(p0: Int, p1: ((Int) -> ExecutorService!)!) defined in io.netty.channel.nio.NioEventLoopGroup
public constructor NioEventLoopGroup(p0: Int, p1: ExecutorServiceFactory!) defined in io.netty.channel.nio.NioEventLoopGroup
public constructor NioEventLoopGroup(p0: Int, p1: Executor!) defined in io.netty.channel.nio.NioEventLoopGroup

**Comment by dkrivoruchko** [comment]
Check if you have correct dependency to info.dvkr.screenstream.data.httpserver.HttpServerThreadFactory
