### ISSUE TITLE
Run error.

### ISSUE THREAD

**Issue by poorvajappja** [dkrivoruchko/ScreenStream#97]
When I run this project in android studio it occurs an error.

`
 Could not determine the dependencies of task ':app:countFirebaseDebugDexMethods'.
> Cannot query the value of this property because it has no value available.

`

**Comment by dkrivoruchko** [comment]
Use Android Studio 4.0 RC1

**Comment by poorvajappja** [comment]
But , I am using android studio version 4.1 canary 9.
![vvv](https://user-images.githubusercontent.com/65843311/82886044-9c3c5600-9f63-11ea-98b4-06f6f58c7dcc.PNG)

Sir , Can I got to Android Studio 4.0 RC1?

**Comment by dkrivoruchko** [comment]
I'm not sure if 4.1 will work

**Comment by poorvajappja** [comment]
Which gradle version you are used in this project ?

when I run it comes like this.

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.`

my gradle version.

![gradle](https://user-images.githubusercontent.com/65843311/82982092-0825c980-a00b-11ea-9d05-3151b466d7b0.PNG)

Build Output :


`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processFirebaseDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\Github\ScreenStream-master\app\src\firebase\google-services.json
  D:\Github\ScreenStream-master\app\src\debug\google-services.json
  D:\Github\ScreenStream-master\app\src\firebaseDebug\google-services.json
  D:\Github\ScreenStream-master\app\src\firebase\debug\google-services.json
  D:\Github\ScreenStream-master\app\src\debug\firebase\google-services.json
  D:\Github\ScreenStream-master\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 23s
5 actionable tasks: 5 executed`

What is the Android Gradle plugin version and Gradle version of this project ?

Give a solution for this error.

**Comment by ashokkumarvel** [comment]
I also have the same error . 

How can I resolve it ?

**Comment by dkrivoruchko** [comment]
You may ignore Deprecated Gradle features were used in this build, making
it incompatible with Gradle 7.0.

And select FirebaseFree build
/ Dmitriy

**Comment by poorvajappja** [comment]
Can you give more information ? 

How to ignore Deprecated Gradle features were used in this build and making it incompatible with Gradle 7.0 ?

I am did not know about this.

I tried . But , I have the same error .

**Comment by ashokkumarvel** [comment]
It comes `  Execution failed for task ':app:processFirebaseDebugGoogleServices'.  `

**Comment by dkrivoruchko** [comment]
Just ignore this `Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.`

To solve this `Execution failed for task ':app:processFirebaseDebugGoogleServices'` switch to build variant `FirebaseFree`
