### ISSUE TITLE
How to remove check box?

### ISSUE THREAD

**Issue by ashokkumarvel** [dkrivoruchko/ScreenStream#99]
![Screenshot_20200621-124000_ScreenStream](https://user-images.githubusercontent.com/65845270/85219002-8fbde880-b3bd-11ea-9b47-cce90158fe4f.jpg)

I want to remove this check box and set a default port number. 

I tryed to remove this check box.

But , an error occurs.

I did not know how to remove this check box.

Help me!!!

**Comment by dkrivoruchko** [comment]
There is no checkbox on server port. Default is 8080

**Comment by poorvajappja** [comment]
I want to set 1234 as a default port.
How can I set 1234 as a default port?

**Comment by dkrivoruchko** [comment]
Tap on server port enter 1234 instead 8080. Tap ok.

**Comment by poorvajappja** [comment]
I want remove this https://user-images.githubusercontent.com/65845270/85219002-8fbde880-b3bd-11ea-9b47-cce90158fe4f.jpg  editText and set 1234 as default.

**Comment by poorvajappja** [comment]
I want to set a port with programmatically.

**Comment by dkrivoruchko** [comment]
Change in this line https://github.com/dkrivoruchko/ScreenStream/blob/1f93d6c256198bf456b55f8a1a6134489b5ea2ae/data/src/main/kotlin/info/dvkr/screenstream/data/settings/Settings.kt#L76

**Comment by ashokkumarvel** [comment]
![20200621_153015](https://user-images.githubusercontent.com/65845270/85221767-42994100-b3d4-11ea-9130-b991f9f00a6f.jpg)

How can I change this blue color to another color?
